### Constnts
@host = 192.168.1.216
@port = 8111
@user = admin
@password = admin

### Hardcode Data
@projectID = project1
@buildTypeID = buildType1

### GET all projects
GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects
Content-Type: application/json
Accept: application/json

### Step 1: create project
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects
Content-Type: application/json
Accept: application/json

{
    "parentProject": {
        "locator": "_Root"
    },
    "name": "{{projectID}}",
    "id": "{{projectID}}",
    "copyAllAssociatedSettings": true
}
### Step 2: create biuld type
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/buildTypes
Content-Type: application/json
Accept: application/json

{
    "id": "{{buildTypeID}}",
    "name": "{{buildTypeID}}",
    "project": {
        "id": "{{projectID}}"
    },
    "parameters": {
        "property": [
            {
                "name": "myBuildParameter",
                "value": "myValue"
            }
        ]
    },
    "steps": {
        "step": [
            {
                "name": "myCommandLineStep",
                "type": "simpleRunner",
                "properties": {
                    "property": [
                        {
                            "name": "script.content",
                            "value": "echo 'Hello World!'"
                        }
                    ]
                }
            }
        ]
    }
}
### Step 3: run build
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/buildQueue
Content-Type: application/json
Accept: application/json

{
	"buildType": {
    	"id": "{{buildTypeID}}"
	}
}